#theme: jekyll-theme-dinky
markdown: kramdown
plugins:
  - jekyll-seo-tag
navigation:
- url: /
  title: Overview
- url: /getting-started/installation.html
  title: Installation
- url: /getting-started/configuration.html
  title: Configuration
- url: /windows/categories/
  title: Transaction Categories