#theme: jekyll-theme-dinky
markdown: kramdown
plugins:
  - jekyll-seo-tag
navigation:
- url: /
  title: Overview
- url: /getting-started/installation.html
  title: Installation
- url: /getting-started/configuration.html
  title: Configuration
- url: /getting-started/common-ui.html
  title: Using the UI
- url: /windows/accounts/
  title: Accounts
- url: /windows/payees/
  title: Payees
- url: /windows/categories/
  title: Transaction Categories
- url: /windows/groups/
  title: Transaction Groups
- url: /windows/securities/
  title: Securities