#ifndef DBDIALECT_H
#define DBDIALECT_H

#include <QSqlDatabase>
#include <QString>

#define PG_ID_TYPE "bigint not null primary key generated by default as identity"
#define MYSQL_ID_TYPE "bigint not null primary key auto_increment"
#define SQLITE_ID_TYPE "integer not null primary key"

#define PG_IN_LIST(column, placeholder) "to_jsonb(" #column ") <@ " #placeholder
#define MYSQL_IN_LIST(column, placeholder) #column " member of (" #placeholder ")"
#define SQLITE_IN_LIST(column, placeholder) #column " in (select value from json_each(" #placeholder "))"

#define SQLITE_SUM "decimal_sum"
#define SQLITE_JSON_ARRAY_AGG "json_group_array"

#define IS_PG(db) db.driverName() == "QPSQL"
#define IS_MYSQL(db) db.driverName() == "QMYSQL"
#define IS_SQLITE(db) db.driverName() == "QSQLITE"

// Requires 3 query variables in scope with the passed suffix and the following prefixes:
//  - pg
//  - mysql
//  - sqlite
#define SELECT_QUERY(db, SqlVarSuffix) \
    (IS_PG(db)) ? pg##SqlVarSuffix : ((IS_MYSQL(db)) ? mysql##SqlVarSuffix : sqlite##SqlVarSuffix)

namespace dbDialect {
    QString createTableSql(const QSqlDatabase &db, QString sqlTemplate);

    QString inList(const QSqlDatabase &db, const char *column, const char *placeholder);

    QString replaceJsonArrayAgg(const QSqlDatabase &db, QString sql);

    QSqlQuery prepareGetByIds(const QSqlDatabase &db, const char *getAllSql, QVariantList ids, const char *idColumn);
};

#endif // DBDIALECT_H
