#include <QSqlQuery>
#include <QSqlDriver>
#include <QRegularExpression>
#include "dbdialect.h"
#include "sql.h"
#include <QDecNumber.hh>

static const auto stockSplitsSql = R"(
select shares_in, shares_out
from stock_split
where security_id = :securityId and date >= :fromDate)";

static void adjustShares(sqlite3_context *context, int argc, sqlite3_value **argv) {
    assert(argc == 3);
    for (int i = 0; i < 3; i++) {
        if (sqlite3_value_type(argv[i]) == SQLITE_NULL) {
            sqlite3_result_null(context);
            return;
        }
    }
    auto db = sqlite3_context_db_handle(context);
    sqlite3_stmt *stmt;
    QDecNumber shares, sharesIn, sharesOut;
    auto securityId = sqlite3_value_int64(argv[0]);
    auto fromDate = (const char *)sqlite3_value_text(argv[1]);
    shares.fromString((const char *)sqlite3_value_text(argv[2]));

    const char * message = "adjust_shares: fetch row failed";
    int status = sqlite3_prepare_v2(db, stockSplitsSql, -1, &stmt, nullptr);
    if (status != SQLITE_OK) message = "adjust_shares: prepare failed";
    else {
        sqlite3_bind_int64(stmt, 1, securityId);
        sqlite3_bind_text(stmt, 2, fromDate, -1, nullptr);
        while ((status = sqlite3_step(stmt)) == SQLITE_ROW) {
            sharesIn.fromString((const char *) sqlite3_column_text(stmt, 0));
            sharesOut.fromString((const char *) sqlite3_column_text(stmt, 1));
            shares = shares * sharesOut / sharesIn;
        }
    }
    sqlite3_finalize(stmt);
    if (status == SQLITE_DONE) {
        sqlite3_result_text(context, shares.toString().constData(), -1, SQLITE_TRANSIENT);
    } else {
        sqlite3_result_error(context, message, -1);
    }
}

namespace dbDialect {
    static const auto pgIdType = "bigint not null primary key generated by default as identity";
    static const auto sqliteIdType = "integer not null primary key";
    static const auto mysqlIdType = "bigint not null primary key auto_increment";

    QString inList(const QSqlDatabase &db, const char *column, const char *placeholder) {
        if (IS_SQLITE(db)) return QString("%0 in (select value from json_each(%1))").arg(column, placeholder);
        else if (IS_PG(db)) return QString("to_jsonb(%0) <@ %1 ").arg(column, placeholder);
        else return QString("%0 member of (%1)").arg(column, placeholder);
    }

    QSqlQuery prepareGetByIds(const QSqlDatabase &db, const char *getAllSql, QVariantList ids, const char *idColumn) {
        QSqlQuery query{db};
        QString sql = getAllSql;
        sql += "\nwhere " + inList(db, idColumn, ":ids");
        query.prepare(sql);
        SQL_BIND_LIST(query, ":ids", ids);
        return query;
    }

    void addDbFunctions(sqlite3 *handle) {
        auto status = sqlite3_create_function_v2(handle, "adjust_shares", 3, SQLITE_UTF8, nullptr, adjustShares, nullptr, nullptr, nullptr);
        if (status != SQLITE_OK) {
            qCritical() << "sqlite3 status:" << status;
        }
    }
}