#ifndef DBDIALECT_H
#define DBDIALECT_H

#include <QSqlDatabase>
#include <QString>
#include <sqlite3.h>

#define PG_ID_TYPE "bigint not null primary key generated by default as identity"
#define MYSQL_ID_TYPE "bigint not null primary key auto_increment"
#define SQLITE_ID_TYPE "integer not null primary key"

#define PG_IN_LIST(column, placeholder) "to_jsonb(" #column ") <@ " #placeholder
#define MYSQL_IN_LIST(column, placeholder) #column " member of (" #placeholder ")"
#define SQLITE_IN_LIST(column, placeholder) #column " in (select value from json_each(" #placeholder "))"

#define DEFAULT_SUM "sum"
#define DEFAULT_GREATEST "greatest"
#define DEFAULT_JSON_ARRAY_AGG "json_arrayagg"

#define SQLITE_SUM "decimal_sum"
#define SQLITE_GREATEST "max"
#define SQLITE_JSON_ARRAY_AGG "json_group_array"

#define PG_DRIVER "QPSQL"
#define MYSQL_DRIVER "QMYSQL"
#define SQLITE_DRIVER "QSQLITE"

#define IS_PG(db) db.driverName() == PG_DRIVER
#define IS_MYSQL(db) db.driverName() == MYSQL_DRIVER
#define IS_SQLITE(db) db.driverName() == SQLITE_DRIVER

// Requires 3 query variables in scope with the passed suffix and the following prefixes:
//  - pg
//  - mysql
//  - sqlite
#define DB_TYPE_QUERY(type, SqlVarSuffix) \
    (type == PG_DRIVER ? pg##SqlVarSuffix : type == MYSQL_DRIVER ? mysql##SqlVarSuffix : sqlite##SqlVarSuffix)

namespace dbDialect {
    QString inList(const QSqlDatabase &db, const char *column, const char *placeholder);

    QSqlQuery prepareGetByIds(const QSqlDatabase &db, const char *getAllSql, QVariantList ids, const char *idColumn);
};

#endif // DBDIALECT_H
