#include <QSqlQuery>
#include <QSqlDriver>
#include <QRegularExpression>
#include "dbdialect.h"
#include "sql.h"

namespace dbDialect {
    static const auto pgIdType = "bigint not null primary key generated by default as identity";
    static const auto sqliteIdType = "integer not null primary key";
    static const auto mysqlIdType = "bigint not null primary key auto_increment";

    QString createTableSql(const QSqlDatabase &db, QString sqlTemplate) {
        if (db.driverName() == "QPSQL") return sqlTemplate.arg(pgIdType);
        if (db.driverName() == "QSQLITE") return sqlTemplate.arg(sqliteIdType);
        return sqlTemplate.arg(mysqlIdType);
    }

    QString inList(const QSqlDatabase &db, const char *column, const char *placeholder) {
        if (db.driverName() == "QSQLITE") return QString("%0 in (select value from json_each(%1))").arg(column, placeholder);
        else if (db.driverName() == "QPSQL") return QString("to_jsonb(%0) <@ %1 ").arg(column, placeholder);
        else return QString("%0 member of (%1)").arg(column, placeholder);
    }

    QSqlQuery prepareGetByIds(const QSqlDatabase &db, const char *getAllSql, QVariantList ids, const char *idColumn) {
        QSqlQuery query{db};
        QString sql = replaceJsonArrayAgg(db, getAllSql);
        sql += "\nwhere " + inList(db, idColumn, ":ids");
        query.prepare(sql);
        SQL_BIND_LIST(query, ":ids", ids);
        return query;
    }

    static const QRegularExpression jsonArrayAggRe{"\\bjson_arrayagg\\b"};

    QString replaceJsonArrayAgg(const QSqlDatabase &db, QString sql) {
        if (db.driverName() == "QSQLITE") sql.replace(jsonArrayAggRe, "json_group_array");
        return sql;
    }
}